"""In-memory PDF rendering for stored quotation snapshots."""

from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.models.quotation import Quotation


def build_quotation_pdf(quotation: Quotation) -> bytes:
    """Render a quotation entirely in memory using stored price snapshots."""
    buffer = BytesIO()
    document = SimpleDocTemplate(
        buffer, pagesize=A4, rightMargin=16 * mm, leftMargin=16 * mm,
        topMargin=15 * mm, bottomMargin=15 * mm,
    )
    styles = getSampleStyleSheet()
    estimate = quotation.estimate
    user = estimate.user
    furniture = estimate.selected_furniture_type
    items = sorted(quotation.items, key=lambda item: item.id)
    primary_names = ", ".join(
        item.material_name_snapshot for item in items if not item.is_alternative
    ) or "None"
    alternative_names = ", ".join(
        item.material_name_snapshot for item in items if item.is_alternative
    ) or "None"

    story = [
        Paragraph("WUE Quotation", styles["Title"]),
        Spacer(1, 5 * mm),
        Table(
            [
                ["Quotation number", quotation.quotation_number],
                ["Created date", quotation.created_at.strftime("%Y-%m-%d")],
                ["Estimate ID", str(quotation.estimate_id)],
                ["Customer", user.full_name or user.username],
                ["Furniture type", furniture.name if furniture else "Not available"],
                ["Dimensions", "Not available in the current estimate schema"],
                ["Selected material(s)", primary_names],
                ["Alternative material(s)", alternative_names],
                ["Status", quotation.status.title()],
            ],
            colWidths=[45 * mm, 120 * mm],
        ),
        Spacer(1, 7 * mm),
    ]

    item_rows = [["Material", "Quantity", "Unit", "Unit price", "Line total"]]
    item_rows.extend(
        [
            item.material_name_snapshot,
            f"{item.quantity:.3f}",
            item.unit_snapshot,
            f"{quotation.currency_code} {item.unit_price_snapshot:.2f}",
            f"{quotation.currency_code} {item.line_total:.2f}",
        ]
        for item in items
    )
    item_table = Table(
        item_rows, repeatRows=1, colWidths=[55 * mm, 25 * mm, 25 * mm, 35 * mm, 35 * mm]
    )
    item_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#D9EAD3")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("ALIGN", (1, 1), (1, -1), "RIGHT"),
                ("ALIGN", (3, 1), (-1, -1), "RIGHT"),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ]
        )
    )
    story.extend([item_table, Spacer(1, 7 * mm)])

    totals = Table(
        [
            ["Material total", f"{quotation.currency_code} {quotation.material_total:.2f}"],
            ["Labor", f"{quotation.currency_code} {quotation.labor_cost:.2f}"],
            ["Logistics", f"{quotation.currency_code} {quotation.logistics_cost:.2f}"],
            ["Subtotal", f"{quotation.currency_code} {quotation.subtotal_before_profit:.2f}"],
            ["Profit percentage", f"{quotation.profit_percentage:.2f}%"],
            ["Profit amount", f"{quotation.currency_code} {quotation.profit_amount:.2f}"],
            ["Grand total", f"{quotation.currency_code} {quotation.grand_total:.2f}"],
        ],
        colWidths=[55 * mm, 45 * mm], hAlign="RIGHT",
    )
    totals.setStyle(
        TableStyle(
            [
                ("ALIGN", (1, 0), (1, -1), "RIGHT"),
                ("LINEABOVE", (0, -1), (-1, -1), 1, colors.black),
                ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
            ]
        )
    )
    story.extend(
        [totals, Spacer(1, 12 * mm), Paragraph("Generated by WUE", styles["Normal"])]
    )
    document.build(story)
    return buffer.getvalue()
