"""create_initial_wue_schema

Revision ID: b8f4d1daabca
Revises: 
Create Date: 2026-07-20 22:43:22.850388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8f4d1daabca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('furniture_types',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('materials',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('current_unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('alternative_material_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('alternative_material_id IS NULL OR alternative_material_id <> id', name='ck_materials_not_own_alternative'),
    sa.CheckConstraint('current_unit_price >= 0', name='ck_materials_current_unit_price'),
    sa.ForeignKeyConstraint(['alternative_material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'admin')", name='ck_users_role'),
    sa.CheckConstraint('char_length(btrim(username)) BETWEEN 3 AND 50', name='ck_users_username_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_index('uq_users_username_lower', 'users', [sa.literal_column('lower(username)')], unique=True)
    op.create_table('estimates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('selected_furniture_type_id', sa.BigInteger(), nullable=True),
    sa.Column('recognized_furniture_type_id', sa.BigInteger(), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('input_method', sa.String(length=20), nullable=False),
    sa.Column('recognition_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("input_method <> 'image_upload' OR image_path IS NOT NULL", name='ck_estimates_image_upload_path'),
    sa.CheckConstraint("input_method IN ('predefined', 'image_upload')", name='ck_estimates_input_method'),
    sa.CheckConstraint("status IN ('draft', 'processing') OR selected_furniture_type_id IS NOT NULL", name='ck_estimates_selected_type_for_completed_status'),
    sa.CheckConstraint("status IN ('draft', 'processing', 'processed', 'quoted')", name='ck_estimates_status'),
    sa.CheckConstraint('(recognized_furniture_type_id IS NULL AND recognition_confidence IS NULL) OR (recognized_furniture_type_id IS NOT NULL AND recognition_confidence IS NOT NULL)', name='ck_estimates_recognition_pair'),
    sa.CheckConstraint('recognition_confidence IS NULL OR recognition_confidence BETWEEN 0 AND 1', name='ck_estimates_recognition_confidence'),
    sa.ForeignKeyConstraint(['recognized_furniture_type_id'], ['furniture_types.id'], ),
    sa.ForeignKeyConstraint(['selected_furniture_type_id'], ['furniture_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('furniture_materials',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('furniture_type_id', sa.BigInteger(), nullable=False),
    sa.Column('material_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity_required', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('wastage_percentage', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_required > 0', name='ck_furniture_materials_quantity'),
    sa.CheckConstraint('wastage_percentage BETWEEN 0 AND 100', name='ck_furniture_materials_wastage'),
    sa.ForeignKeyConstraint(['furniture_type_id'], ['furniture_types.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('furniture_type_id', 'material_id', name='uq_furniture_materials_type_material')
    )
    op.create_table('inventory',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('material_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity_available', sa.Numeric(precision=12, scale=3), server_default='0.000', nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=12, scale=3), server_default='0.000', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_available >= 0', name='ck_inventory_quantity_available'),
    sa.CheckConstraint('reorder_level >= 0', name='ck_inventory_reorder_level'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id')
    )
    op.create_table('quotations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('quotation_number', sa.String(length=30), nullable=False),
    sa.Column('estimate_id', sa.BigInteger(), nullable=False),
    sa.Column('material_total', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('labor_cost', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('logistics_cost', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('subtotal_before_profit', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('profit_percentage', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False),
    sa.Column('profit_amount', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('currency_code', sa.CHAR(length=3), server_default='PHP', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency_code ~ '^[A-Z]{3}$'", name='ck_quotations_currency_code'),
    sa.CheckConstraint("status IN ('draft', 'issued', 'accepted', 'rejected', 'expired')", name='ck_quotations_status'),
    sa.CheckConstraint('grand_total >= 0', name='ck_quotations_grand_total'),
    sa.CheckConstraint('labor_cost >= 0', name='ck_quotations_labor_cost'),
    sa.CheckConstraint('logistics_cost >= 0', name='ck_quotations_logistics_cost'),
    sa.CheckConstraint('material_total >= 0', name='ck_quotations_material_total'),
    sa.CheckConstraint('profit_amount >= 0', name='ck_quotations_profit_amount'),
    sa.CheckConstraint('profit_percentage BETWEEN 0 AND 100', name='ck_quotations_profit_percentage'),
    sa.CheckConstraint('subtotal_before_profit >= 0', name='ck_quotations_subtotal_before_profit'),
    sa.CheckConstraint('valid_until IS NULL OR valid_until >= CAST(created_at AS DATE)', name='ck_quotations_valid_until'),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quotation_number')
    )
    op.create_table('quotation_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('quotation_id', sa.BigInteger(), nullable=False),
    sa.Column('material_id', sa.BigInteger(), nullable=False),
    sa.Column('furniture_material_id', sa.BigInteger(), nullable=True),
    sa.Column('material_name_snapshot', sa.String(length=100), nullable=False),
    sa.Column('unit_snapshot', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_alternative', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('line_total >= 0', name='ck_quotation_items_line_total'),
    sa.CheckConstraint('quantity > 0', name='ck_quotation_items_quantity'),
    sa.CheckConstraint('unit_price_snapshot >= 0', name='ck_quotation_items_unit_price_snapshot'),
    sa.ForeignKeyConstraint(['furniture_material_id'], ['furniture_materials.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotation_items')
    op.drop_table('quotations')
    op.drop_table('inventory')
    op.drop_table('furniture_materials')
    op.drop_table('estimates')
    op.drop_index('uq_users_username_lower', table_name='users')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_table('users')
    op.drop_table('materials')
    op.drop_table('furniture_types')
    # ### end Alembic commands ###
